[tool.poetry]
name = "study"
version = "0.1.0"
description = ""
authors = ["Chanjongp <pcj0198@daum.net>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pydantic = "^1.10.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
